/**
 * GENERATED FILE. This file was generated by @kayteh/bento. Editing it is a bad idea.
 * @generated
 */
import Bento, { IBentoTransport } from '../..'
export type Ok = {
  ok?: boolean
}

export type None = {
}

export type PostQuery = {
  id: string
}

export type Post = {
  id?: string
  content: string
}

export interface ICrudTestService {
  createPost (ctx: any, request: Post): Promise<Post> | Post
  listPosts (ctx: any, request: None): Promise<Post> | Post
  getPost (ctx: any, request: PostQuery): Promise<Post> | Post
  updatePost (ctx: any, request: Post): Promise<Post> | Post
  deletePost (ctx: any, request: PostQuery): Promise<Ok> | Ok
}
export class CrudTestClient {
  static __SERVICE__: string = 'CrudTest'
  constructor (private bento: Bento, private transport?: IBentoTransport) {}
  async createPost (request: Post): Promise<Post> {
    return this.bento.makeRequest(this.transport || undefined, 'CrudTest', 'CreatePost', request)
  }
  async listPosts (request: None): Promise<Post> {
    return this.bento.makeRequest(this.transport || undefined, 'CrudTest', 'ListPosts', request)
  }
  async getPost (request: PostQuery): Promise<Post> {
    return this.bento.makeRequest(this.transport || undefined, 'CrudTest', 'GetPost', request)
  }
  async updatePost (request: Post): Promise<Post> {
    return this.bento.makeRequest(this.transport || undefined, 'CrudTest', 'UpdatePost', request)
  }
  async deletePost (request: PostQuery): Promise<Ok> {
    return this.bento.makeRequest(this.transport || undefined, 'CrudTest', 'DeletePost', request)
  }
}
