/**
 * GENERATED FILE. This file was generated by @kayteh/bento. Editing it is a bad idea.
 * @generated
 */
import Bento, { IBentoTransport } from '../..'
export type HelloRequest = {
  name?: string
}

export type HelloReply = {
  message?: string
}

export interface IHelloWorldService {
  sayHello (ctx: any, request: HelloRequest): Promise<HelloReply> | HelloReply
}
export class HelloWorldClient {
  static __SERVICE__: string = 'HelloWorld'
  constructor (private bento: Bento, private transport?: IBentoTransport) {}
  async sayHello (request: HelloRequest): Promise<HelloReply> {
    return this.bento.makeRequest(this.transport || undefined, 'HelloWorld', 'SayHello', request)
  }
}
